services:
  - type: web
    name: routeopt-api
    runtime: python
    plan: free
    region: oregon

    rootDir: route_optimizer

    buildCommand: pip install -r requirements.txt

    startCommand: gunicorn config.wsgi:application --config gunicorn.conf.py

    healthCheckPath: /health/

    autoDeployTrigger: commit

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9

      - key: DJANGO_DEBUG
        value: "False"

      - key: MAPBOX_TOKEN
        sync: false

      - key: DJANGO_SECRET_KEY
        sync: false

      - key: GEOCODE_CACHE_PATH
        value: geocode_cache.db

      - key: FUEL_CSV_PATH
        value: data/fuel_prices.csv

      - key: WEB_CONCURRENCY
        value: "1"
